/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author RYZEN
 */
public class PanelClientes extends javax.swing.JPanel {
    DefaultListModel modeloClientes;
    
    public PanelClientes() {
        initComponents();
        modeloClientes = new DefaultListModel();
        listaClientes.setModel(modeloClientes);     
    }
    
    public void cambiarTextoActualizar(){    
        if("ACTUALIZAR".equals(btnActualizarCliente.getText())){
            btnActualizarCliente.setText("ACEPTAR");
        }else{
            btnActualizarCliente.setText("ACTUALIZAR");
        }
    }
    
    public void setGeneroSeleccionado(String _genero){
         comboGeneroCliente.setSelectedItem(_genero);
    }
    
    public void setTxtID(String _txt)
    {
        txtID.setText(_txt);
    }
    
    public String getTxtID()
    {
        return txtID.getText();
    }

    /**
     * Creates new form PanelClientes
     */
    public void cambiarEstadoCampos(boolean estado){
        txtID.setEnabled(estado);
        txtNombresCliente.setEnabled(estado);
        txtCorreoCliente.setEnabled(estado);
        txtTelefonoCliente.setEnabled(estado);
        comboGeneroCliente.setEnabled(estado);
        txtEdadCliente.setEnabled(estado);
        txtNumeroComprasCliente.setEnabled(estado);
    }
    
    public void setBtnActualizar(String _txt)
    {
        btnActualizarCliente.setText(_txt);
    }
    
    public void habilitarBotonActualizar(boolean estado){
        btnActualizarCliente.setEnabled(estado);
    }
    
    public void habilitarBotonBorrar(boolean estado){
        btnBorrarCliente.setEnabled(estado);
    }
    
    public void habilitarBotonCrear(boolean estado){
        btnCrearCliente.setEnabled(estado);
    }
    
    public String getNombres(){
        return txtNombresCliente.getText();
    }
    
    public void setNombres(String nombres){
        txtNombresCliente.setText(nombres);
    }
    
    
    public String getCorreo(){
        return txtCorreoCliente.getText();
    }
    
    public void setCorreo(String correo){
        txtCorreoCliente.setText(correo);
    }
    
    public String getTelefono(){
        return txtTelefonoCliente.getText();
    }
    
    public void setTelefono(String telefono){
        txtTelefonoCliente.setText(telefono);
    }
    
    public int getEdad(){
        return Integer.parseInt(txtEdadCliente.getText());
    }
    
    public void setEdad(int edad){
        txtEdadCliente.setText(String.valueOf(edad));
    }
    
    public int getNumeroCompras(){
        return Integer.parseInt(txtNumeroComprasCliente.getText());
    }
    
    public void setNumeroCompras(int numeroCompras){
        txtNumeroComprasCliente.setText(String.valueOf(numeroCompras));
    }
    
    public void llenarComboGenero(ArrayList<String> generos){
        for (String genero : generos)
            {
                comboGeneroCliente.addItem(genero);
            }
    }
    
    public void vaciarCampos()
    {
        txtID.setText("");
        txtNombresCliente.setText("");
        txtEdadCliente.setText("");
        txtCorreoCliente.setText("");
        txtNumeroComprasCliente.setText("");
        txtTelefonoCliente.setText("");
        comboGeneroCliente.setSelectedItem("No establecido");
    }
    
    public String getGeneroSeleccionado(){
        return comboGeneroCliente.getSelectedItem().toString();
    }
    
    public String getClienteSeleccionado(){
        return listaClientes.getSelectedValue();
    }
    
    public void llenarListaClientes(ArrayList<String> clientes){
        modeloClientes.removeAllElements();
        for (String cliente : clientes)
            {
                modeloClientes.addElement(cliente);
            }
    }
    
    public void addBtnActualizarListener(ActionListener listenControles){
        btnActualizarCliente.addActionListener(listenControles);
    }
    
    public void addBtnBorrarListener(ActionListener listenControles){
        btnBorrarCliente.addActionListener(listenControles);
    }
    
    public void addBtnCrearListener(ActionListener listenControles){
        btnCrearCliente.addActionListener(listenControles);
    }

    public void addListaClientesListener(ListSelectionListener listenSelectionController){
        listaClientes.addListSelectionListener(listenSelectionController);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        lblListaClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombresCliente = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        txtTelefonoCliente = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        comboGeneroCliente = new javax.swing.JComboBox<>();
        lblGenero1 = new javax.swing.JLabel();
        txtEdadCliente = new javax.swing.JTextField();
        lblEdad1 = new javax.swing.JLabel();
        txtNumeroComprasCliente = new javax.swing.JTextField();
        btnCrearCliente = new javax.swing.JButton();
        btnActualizarCliente = new javax.swing.JButton();
        btnBorrarCliente = new javax.swing.JButton();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblListaClientes1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaClientes);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 350));

        lblListaClientes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblListaClientes.setText("INFORMACIÓN");
        add(lblListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(176, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCorreo.setText("  Correo:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lblNombres.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNombres.setText("Nombre:");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        txtNombresCliente.setEnabled(false);
        jPanel1.add(txtNombresCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, -1));

        txtCorreoCliente.setEnabled(false);
        jPanel1.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, -1));

        lblEdad.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblEdad.setText(" No. Compras:");
        jPanel1.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        txtTelefonoCliente.setEnabled(false);
        jPanel1.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, -1));

        lblTelefono1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTelefono1.setText("Teléfono:");
        jPanel1.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        comboGeneroCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No establecido", "M", "F" }));
        comboGeneroCliente.setEnabled(false);
        jPanel1.add(comboGeneroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, -1));

        lblGenero1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblGenero1.setText("Género:");
        jPanel1.add(lblGenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txtEdadCliente.setEnabled(false);
        jPanel1.add(txtEdadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, -1));

        lblEdad1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblEdad1.setText("Edad:");
        jPanel1.add(lblEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        txtNumeroComprasCliente.setEnabled(false);
        jPanel1.add(txtNumeroComprasCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 220, -1));

        btnCrearCliente.setBackground(new java.awt.Color(0, 86, 158));
        btnCrearCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrearCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCliente.setText("CREAR");
        btnCrearCliente.setBorder(null);
        jPanel1.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 40));

        btnActualizarCliente.setBackground(new java.awt.Color(0, 86, 158));
        btnActualizarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarCliente.setText("ACTUALIZAR");
        btnActualizarCliente.setBorder(null);
        btnActualizarCliente.setEnabled(false);
        jPanel1.add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 40));

        btnBorrarCliente.setBackground(new java.awt.Color(0, 86, 158));
        btnBorrarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBorrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarCliente.setText("BORRAR");
        btnBorrarCliente.setBorder(null);
        btnBorrarCliente.setEnabled(false);
        jPanel1.add(btnBorrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 120, 40));

        lblID.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblID.setText("ID:");
        jPanel1.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        txtID.setEnabled(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 440, 350));

        lblListaClientes1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblListaClientes1.setText("LISTA DE CLIENTES");
        add(lblListaClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnBorrarCliente;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JComboBox<String> comboGeneroCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblGenero1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblListaClientes;
    private javax.swing.JLabel lblListaClientes1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtEdadCliente;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JTextField txtNumeroComprasCliente;
    private javax.swing.JTextField txtTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
