/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 *
 * @author RYZEN
 */
public class PanelCrearProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelCrearProducto
     */
    public PanelCrearProducto() {
        initComponents();
    }
    
    public void activarBotonCrear(boolean estado){
        btnCrearProducto.setEnabled(estado);
    }
    
    
    public String getNombre(){
        return txtNombreProducto.getText();
    }
    
    public void setNombre(String nombre){
        txtNombreProducto.setText(nombre);
    }
    
    public int getNumeroVendidos(){
        return Integer.parseInt(txtVendidosProducto.getText());
    }
    
    public void setNumeroVendidos(String numeroVendidos){
        txtVendidosProducto.setText(numeroVendidos);
    }
    
    public int getInventario(){
        return Integer.parseInt(txtInventarioProducto.getText());
    }
    
    public void setInventario(int numeroInventario){
        txtInventarioProducto.setText(String.valueOf(numeroInventario));
    }
    
    public float getPrecioCompra(){
        return Float.parseFloat(txtPrecioCompra.getText());
    }
    
    public void setPrecioCompra(String precio)
    {
        txtPrecioCompra.setText(String.valueOf(precio));
    }
    
    public float getPrecioVenta()
    {
        return Float.parseFloat(txtPrecioVenta.getText());
    }
    
    public void setPrecioVenta(String _txt)
    {
        txtPrecioVenta.setText(_txt);
    }
    
    public void llenarComboProveedores(ArrayList<String> proveedores){
        comboProvProducto.removeAllItems();
        for (String pr: proveedores)
            {
                comboProvProducto.addItem(pr);
            }
    }
    
    public String getProveedorSeleccionado(){
        return comboProvProducto.getSelectedItem().toString();
    }
    
    public void addBtnCrearListener(ActionListener listenControles){
        btnCrearProducto.addActionListener(listenControles);
    }
    
    public void addBtnVolverListener(ActionListener listenControles){
        btnVolver.addActionListener(listenControles);
    }
    
    public void addBtnCancelarListener(ActionListener listenControles){
        btnCancelar.addActionListener(listenControles);
    }
    
    public String getCodigo()
    {
        return txtCodigo.getText();
    }
    
    public void setCodigo(String _txt)
    {
        txtCodigo.setText(_txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCorreo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtVendidosProducto = new javax.swing.JTextField();
        lblTelefono1 = new javax.swing.JLabel();
        txtInventarioProducto = new javax.swing.JTextField();
        lblNumeroVentas = new javax.swing.JLabel();
        lblPrecioCompra = new javax.swing.JLabel();
        txtPrecioCompra = new javax.swing.JTextField();
        comboProvProducto = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnCrearProducto = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblPrecioCompra1 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListaClientes.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblListaClientes.setText("CREAR PRODUCTO");
        add(lblListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(176, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCorreo.setText("  Proveedor:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        lblNombres.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNombres.setText("  Nombre:");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 190, -1));
        jPanel1.add(txtVendidosProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, -1));

        lblTelefono1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTelefono1.setText("  Vendidos:");
        jPanel1.add(lblTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));
        jPanel1.add(txtInventarioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, -1));

        lblNumeroVentas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblNumeroVentas.setText("  Inventario:");
        jPanel1.add(lblNumeroVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        lblPrecioCompra.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblPrecioCompra.setText("   Precio Compra:");
        jPanel1.add(lblPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));
        jPanel1.add(txtPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 190, -1));

        comboProvProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboProvProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 190, -1));

        btnCancelar.setBackground(new java.awt.Color(0, 86, 158));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, 40));

        btnCrearProducto.setBackground(new java.awt.Color(0, 86, 158));
        btnCrearProducto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCrearProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProducto.setText("CREAR");
        btnCrearProducto.setBorder(null);
        jPanel1.add(btnCrearProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 120, 40));

        lblCodigo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCodigo.setText("Código:");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 190, -1));

        lblPrecioCompra1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblPrecioCompra1.setText("   Precio Venta:");
        jPanel1.add(lblPrecioCompra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));
        jPanel1.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 190, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 440, 350));

        btnVolver.setBackground(new java.awt.Color(0, 86, 158));
        btnVolver.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("VOLVER");
        btnVolver.setBorder(null);
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboProvProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblListaClientes;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumeroVentas;
    private javax.swing.JLabel lblPrecioCompra;
    private javax.swing.JLabel lblPrecioCompra1;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtInventarioProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtVendidosProducto;
    // End of variables declaration//GEN-END:variables

    public void setInventario(String string) {
        txtInventarioProducto.setText("");
    }
    
    public void vaciarCampos()
    {
        setCodigo("");
        setNombre("");
        setPrecioCompra("");
        setPrecioVenta("");
        setInventario("");
        setNumeroVendidos("");
    }

}
