/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author RYZEN
 */
public class PanelTiendaVender extends javax.swing.JPanel {
    DefaultListModel modeloProductos;
    DefaultListModel modeloClientes;

    /**
     * Creates new form PanelTiendaVender
     */
    public PanelTiendaVender() {
        initComponents();
        modeloProductos = new DefaultListModel();
        modeloClientes = new DefaultListModel();
        listaProductos.setModel(modeloProductos);
        listaClientes.setModel(modeloClientes);
    }
    
    public void llenarComboMetodoPago(ArrayList<String> metodosPago){
        for (String metodo : metodosPago)
            {
                comboMetodoPago.addItem(metodo);
            }
    }
    
    public String getMetodoPagoSeleccionado(){
        return comboMetodoPago.getSelectedItem().toString();
    }
    
    public String getProductoSeleccionado(){
        return listaProductos.getSelectedValue();
    }
    
    public void llenarListaProductos(ArrayList<String> productos){
        modeloProductos.removeAllElements();
        for (String producto : productos)
            {
                System.out.println("Pusé un elemento");
                modeloProductos.addElement(producto);
            }
    }
    
    public String getClienteSeleccionado(){
        return listaClientes.getSelectedValue();
    }

    
    public void llenarListaClientes(ArrayList<String> clientes){
        modeloClientes.removeAllElements();
        for (String cliente : clientes)
            {
                modeloClientes.addElement(cliente);
            }
    }
    
    public void activarBotonAceptarCompra(boolean estado){
        btnAceptarCompra.setEnabled(estado); 
    }
    
    public void activarBotonVerCliente(boolean estado){
        btnVerCliente.setEnabled(estado); 
    }
    
    public int getPrecioPagar(){
        return Integer.parseInt(txtPrecioPagar.getText());
    }
    
    public void setPrecioPagar(float precioTotal){
        txtPrecioPagar.setText(String.valueOf(precioTotal));
    }
    
    public void addBtnCrearClienteListener(ActionListener listenControles){
        btnCrearCliente.addActionListener(listenControles);
    }
    
    public void addBtnAceptarCompraListener(ActionListener listenControles){
        btnAceptarCompra.addActionListener(listenControles);
    }
    
    public void addBtnVerClienteListener(ActionListener listenControles){
        btnVerCliente.addActionListener(listenControles);
    }
    
    public void addBtnRegresarListener(ActionListener listenControles){
        btnRegresar.addActionListener(listenControles);
    }
    
    public void addListaClientesListener(ListSelectionListener listenSelectionController){
        listaClientes.addListSelectionListener(listenSelectionController);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        lblListaProductos = new javax.swing.JLabel();
        Checking = new javax.swing.JPanel();
        txtPrecioPagar = new javax.swing.JTextField();
        lblPrecioPagar1 = new javax.swing.JLabel();
        btnAceptarCompra = new javax.swing.JButton();
        comboMetodoPago = new javax.swing.JComboBox<>();
        lblPrecioPagar2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientes = new javax.swing.JList<>();
        btnVerCliente = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaProductos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 310));

        lblListaProductos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblListaProductos.setText("LISTA DE PRODUCTOS");
        add(lblListaProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Checking.setBackground(new java.awt.Color(176, 230, 253));
        Checking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecioPagar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPrecioPagar.setEnabled(false);
        Checking.add(txtPrecioPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 210, -1));

        lblPrecioPagar1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblPrecioPagar1.setText("Precio a Pagar: ");
        Checking.add(lblPrecioPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnAceptarCompra.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnAceptarCompra.setText("ACEPTAR");
        btnAceptarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAceptarCompra.setEnabled(false);
        Checking.add(btnAceptarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 390, 30));

        comboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TARJETA DE CRÉDITO", "TARJETA DE DÉBITO" }));
        Checking.add(comboMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, -1));

        lblPrecioPagar2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblPrecioPagar2.setText("Metodo de Pago:");
        Checking.add(lblPrecioPagar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        add(Checking, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 430, 150));

        jPanel1.setBackground(new java.awt.Color(176, 230, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClientes.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblClientes.setText("Clientes:");
        jPanel1.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        listaClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 280, 170));

        btnVerCliente.setText("Ver Cliente");
        btnVerCliente.setEnabled(false);
        jPanel1.add(btnVerCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 110, 40));

        btnCrearCliente.setText("Crear Cliente");
        jPanel1.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 430, 230));

        btnRegresar.setBackground(new java.awt.Color(176, 230, 253));
        btnRegresar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 382, 230, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Checking;
    private javax.swing.JButton btnAceptarCompra;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerCliente;
    private javax.swing.JComboBox<String> comboMetodoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblListaProductos;
    private javax.swing.JLabel lblPrecioPagar1;
    private javax.swing.JLabel lblPrecioPagar2;
    private javax.swing.JList<String> listaClientes;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField txtPrecioPagar;
    // End of variables declaration//GEN-END:variables
}
